### ISSUE TITLE
Improve documentation by additional hierarchy

### ISSUE THREAD

**Issue by schlichtanders** [JuliaAI/MLJ.jl#1094]
Just looked at the documentation and was overwhelmed by all the section titles. It is just too much I think.

Maybe someone can create an additional nesting to simplify the navigation of the documentation?

**Comment by ablaom** [comment]
Yeah, this is a fair criticism. 

cc @EssamWisam

**Comment by schlichtanders** [comment]
Any plans?
I really feel hesitant recommending MLJ to others new to Julia because of this.

I know that MLJ is the most complete and best maintained julia meta package for machine learning, but still people just expect that they can go to the documentation and are guided instead of overwhelmed.

**Comment by EssamWisam** [comment]
@schlichtanders 
Sorry if this came a little late. Yes, it's straightforward but we are possibly planning (in the short-term) for other big changes for the documentation/landing page and this or something just as convenient will be one of them.

Until we get to work on that (hopefully soon), I highly recommend that you rely on the categorization found in the [homepage](https://alan-turing-institute.github.io/MLJ.jl/dev/) of the documentation which should be easy to navigate and understand.

**Comment by ablaom** [comment]
Just a note that the grouping of topics on the landing page (not the left menu) are not a strict hierarchy, as the same topic can appear under multiple headings. I'm not wedded to this idea but I do find it personally useful. For example, in MLJ, tuning is a model wrapper, so naturally appears under "Composition". But this may be a novelty for new users, who may be more likely to find it under "Meta-algorithms". 

I wonder if (in addition to adding a heirarchy) we can mitigate the overwhelming experience reported by funnelling new users more aggressively to the "Learn MLJ" page (which has a small link at the top at present). So, on the landing page there could be just 4 very large prominent options:

INSTALL 
LEARN
REFERENCE
MODEL BROWSER

Just brainstorming here. Thoughts?
