### ISSUE TITLE
Remove `info(rms)` from the cheatsheet

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJ.jl#1117]
The `info` method can no longer be called on a measure. One can just do `?rms` if you know the name of the measure or an alias, and you can do `measures("rms")` do search for those measures with "rms" in the doc-string. See also https://juliaai.github.io/StatisticalMeasures.jl/dev/tools/#StatisticalMeasures.measures

**Comment by ablaom** [comment]
cc @abhro Maybe you can include this.

**Comment by abhro** [comment]
Done in 18e9c9f!

**Comment by ablaom** [comment]
Thank you 🙏🏾

**Comment by ablaom** [comment]
There's a second place it occurs:

https://github.com/JuliaAI/MLJ.jl/blob/18e9c9ff1208623de170c6302c033ae45c551bc4/docs/src/mlj_cheatsheet.md?plain=1#L299
