### ISSUE TITLE
Add Missingness Encoder Transformer

### ISSUE THREAD

**Issue by EssamWisam** [JuliaAI/MLJ.jl#1133]
### Motivation
In many settings it's useful to treat missingness as a new category when it affects a categorical column. It would be great to have some transformer (with a meaningful name) that transforms missing values in each column of a given table into a new category (level) for that column.

This would make it possible to use encoders or machine learning models that don't have a default way to deal with missingness and it's a popular strategy to treat missingness meaningfully instead of using imputation.

**Comment by ablaom** [comment]
Happy to provide guidance to a new contributor. The API for implementing a new model is documented [here](https://juliaai.github.io/MLJModelInterface.jl/dev/). You can find other transformer implementations [here](https://github.com/JuliaAI/MLJModels.jl/blob/dev/src/builtins/Transformers.jl).
