### ISSUE TITLE
Migrate MLJ from alan-turing-institute to JuliaAI?

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJ.jl#829]
This is the last remaining repo in the MLJ [eco-system](https://github.com/alan-turing-institute/MLJ.jl#the-mlj-universe) not now under the JuliaAI umbrella.

**Comment by zsz00** [comment]
Hope move MLJ to JuliaAI !!

**Comment by zsz00** [comment]
What is the schedule now?

**Comment by ablaom** [comment]
@zsz00 I think the urgency has gone out of this for the moment. Is there a particular reason you would like or need this?

cc @vollmersj

**Comment by zsz00** [comment]
I found the [issue-765](https://github.com/alan-turing-institute/MLJ.jl/issues/765#issue-847753339) is closed. 
I think moving MLJ is part of that plan as well. 
MLJ is the heart and soul of  JuliaAI group. Hope move MLJ to JuliaAI !

**Comment by ablaom** [comment]
Closed as complete.
