### ISSUE TITLE
For 0.17 release

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJ.jl#864]
- [x] #861
 - [x] update compat for MLJBase 0.19 when released
 - [x] update compat for OpenML to 0.2
 - [x] update compat for MLJEnsembles to 0.2
 - [x] Manual 

Release notes:

---

Bumps the versions of the following dependencies:

- [MLJBase 0.19](https://github.com/JuliaAI/MLJBase.jl/releases/tag/v0.19.0)
- [MLJEnsembles 0.2](https://github.com/JuliaAI/MLJEnsembles.jl/releases/tag/v0.2.0)
- [MLJModels 0.15](https://github.com/JuliaAI/MLJModels.jl/releases/tag/v0.15.0)
- [OpenML 0.2](https://github.com/JuliaAI/OpenML.jl/releases/tag/v0.2.0)
- [ScientificTypes 3](https://github.com/JuliaAI/ScientificTypes.jl/releases/tag/v3.0.0)

Following are the changes relevant to most users. Developers and advanced users can refer to the release notes linked above for a complete list.

- (**breaking**) `schema(X)` no longer includes the `nrows` property. Use `nrows(X)` instead (https://github.com/JuliaAI/MLJBase.jl/issues/698)
- (**mildly breaking**) `unpack(table, p1, p2, ...)` now includes an extra component in its return value, namely a table with all columns not selected by any of the predicates `p1, p2, ... ` Frequently, users' existing code will safely ignore the extra component (https://github.com/JuliaAI/MLJBase.jl/issues/691)
- (**breaking**) Change syntax `EnsembleModel(atom=...)` to `EnsembleModel(model=...)` for consistency with other MLJ model wrappers (eg, `TunedModel`) but additionally allow passing model as non-keyword argument, as in `EnsembleModel(my_tree, ...)`.
- (**breaking**) The default `scale` for unbounded `NumericRange`s is changed from `:log` to `:log10` (https://github.com/JuliaAI/MLJBase.jl/issues/677). 
- (**breaking**) Remove deprecated code for exporting learning networks by hand (https://github.com/JuliaAI/MLJBase.jl/issues/643), which should instead be achieved using `return!` method ([docs](https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/#Method-II:-Finer-control-(advanced))). 
- (**mildly breaking**) The `range(model, :hyperparameter, ...)` constructor now tries to infer type information for the range from the corresponding `model` struct field type for `:hyperparameter`, rather than from the type of the current *value* (https://github.com/JuliaAI/MLJBase.jl/issues/666)
- (**breaking**) Dissallow previously deprecated use of `wrapped_model=...` in `BinaryThresholdPredictor`. Correct syntax is `BinaryThresholdPredictor(model=...)` or `BinaryThresholdPredictor(model, ...)` (https://github.com/JuliaAI/MLJModels.jl/421)

- (**enhancement**) Add a new `Pipeline` type for constructing pipelines without macros. Pipelines are to be constructed using the syntax `model1 |> model2 |> ...` or with the constructor `Pipeline` which exposes more options. The `@pipeline` macro is deprecated (https://github.com/JuliaAI/MLJBase.jl/issues/664)
- (**enhancement**) Add the metamodel `TransformedTargetModel` for wrapping supervised models in transformations of the target variable, which can be *learned* transformations (eg, standardisation). Previously this functionality was available as part of `@pipeline` (https://github.com/JuliaAI/MLJBase.jl/issues/678)
- (**enhancement**) The `partition` function can now be called with a tuple of data arguments, for "synchronised" partitioning, but this requires specifying `multi=true` (because some tables are tuples) as in `(Xtrain, ytrain), (Xtest, ytest) = partition((X, y), rng=123, multi=true)` (https://github.com/JuliaAI/MLJBase.jl/issues/696)
- (**enhancement**) Create a way to include the state, after training, of arbitrary nodes of a learning network, in the report of a model created by exporting the learning network (https://github.com/JuliaAI/MLJBase.jl/issues/644)
- (**new models**) Add the following new models to the registry from MLJText.jl: `BM25Transformer`, `BagOfWordsTransformer` (https://github.com/JuliaAI/MLJModels.jl/419)
- (**enhancement**) Implement the Tables.jl interface for objects returned by `schema` (https://github.com/JuliaAI/ScientificTypes.jl/pull/174)

---

Post-release:

- [x] update examples/lightning_tour/ https://github.com/alan-turing-institute/MLJ.jl/pull/886
- [x] Binder example @ablaom (removed)
- [x] Update DataScienceTutorials.jl @OkonSamuel 
- [x] Update MLJTutorial.jl
- [x] Update ablaom/HelloJulia.jl
- [ ] Update readme for [ShapML.jl](https://github.com/nredell/ShapML.jl) https://github.com/nredell/ShapML.jl/pull/16
- [x] Update readme for TableTransformers.jl (see bottom of the readme page) https://github.com/JuliaML/TableTransforms.jl/pull/20
- [x] Update https://expandingman.gitlab.io/Shapley.jl/ (unnecessary)

**Comment by zsz00** [comment]
What is the state now ?
